name: Build and test
run-name: ${{ github.actor }} is running the build and test for frontend

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
