name: build-docker-artifact.yml
run-name: ${{ github.actor }} pushed to main — build Next.js and Docker image

on:
  push:

jobs:
  build_nextjs:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: nextjs-build
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm and dependencies, build Next.js
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: |
            .next
            node_modules
            package.json
            pnpm-lock.yaml

  build_docker:
    needs: build_nextjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Next.js build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./

      - name: Build Docker image
        run: |
          docker build -t cosh_scraper_frontend:latest .

      - name: Save Docker image to tarball
        run: docker save cosh_scraper_frontend:latest -o cosh_scraper_frontend.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: cosh_scraper_frontend.tar
