name: build-docker-image.yml
run-name: ${{ github.actor }} pushed to main — build Next.js and Docker image

on:
  push:
#    branches:
#      - main

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm and dependencies, build Next.js
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} -t ${{ secrets.DOCKERHUB_USERNAME }}/cosh_scraper:frontend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cosh_scraper:frontend
